### ISSUE TITLE
OZZipException, Error reading 'countries/0/0/0.pbf' in the zipfile

### ISSUE THREAD

**Issue by peterdev2** [jaysquared/mapbox-gl-ios-offline-example#1]
I tried your offline example and I get: Terminating app due to uncaught exception 'OZZipException', reason: 'Error reading 'countries/0/0/0.pbf' in the zipfile' I checked the zip file and countries/0/0/0.pbf is definitely there. Did you come across this yourself? any help is much appreciated.

**Comment by jaysquared** [comment]
Try an earlier Version of objective-zip before they updated the underlying library.

**Comment by peterdev2** [comment]
Installed version 1.0.3 and that works. Awesome, many thanks. 
(Any reason for that, do you by any chance know?)

**Comment by jaysquared** [comment]
I just discovered it, because at the time I published this, the update was not yet out.

But the zip library is an interchangeable part. There are others out there. You could also unzip the file to the documents folder and retrieve them from there.

**Comment by jaysquared** [comment]
I amended the Podfile to specify that version of objective-zip.

**Comment by ohelli** [comment]
Apparently the arrow needs to be removed, it still updated to the latest version.
With `pod 'objective-zip', '1.0.3'` it works as intended.

**Comment by jaysquared** [comment]
Yeah you are right. I updated the Podfile.
