### ISSUE TITLE
Question and Help

### ISSUE THREAD

**Issue by randyhbh** [jaysquared/mapbox-gl-ios-offline-example#2]
Hello Jonathan great job with this app, this is exactly what i needed. I have read your article in Medium, and downloaded your sample application and studied it very carefully. But I have some questions about this.

- there will be a way to update the map once the application is installed on the iphone, if so, it will be necessary to restart the web server. 

I do not know if when the article was written and the application was made, Mapbox's off-line mapping feature existed. If not, you think it will be possible to achieve the same functionality using that feature???.

Sorry if my question are in some way stupid, but i am relative new in ios development and so more working with offline maps in a world fully connected to internet.

Regards

**Comment by jaysquared** [comment]
Hey Randy,

Just cruising on a boat around the Great Barrier Reef, so this is just a quick answer. 

You can put the zip file in your documents folder on first install and then update that. Just adjust the path in the webserver. 

I don't use any of the offline functionality or the mapbox server.

Cheers,
Jonathan

**Comment by randyhbh** [comment]
thanks for your response and advice.
If I have more doubts, can I contact you?

**Comment by jaysquared** [comment]
Just post it in here, so everyone can profit from it.

Jonathan

**Comment by randyhbh** [comment]
hi again, i am trying to build the app for deployment target iOS 9.0 but give this warning.  
- Value Conversion issue
	…/mapbox-gl-ios-offline-example-master 2/OfflineMaps/AppDelegate.m:42:98: Implicit conversion loses integer precision: 'unsigned long long' to 'NSUInteger' (aka 'unsigned int’)
(i fixed this warning allready)

and when running the app is terminating with uncaught exception of type OZZipException terminating with uncaught exception of type OZZipException this is the output:

OfflineMaps[1811:81727] *** Terminating app due to uncaught exception 'OZZipException', reason: 'Error reading 'countries/0/0/0.pbf' in the zipfile'

UPDATE: i fix the OZZipException, now the app finsh to load.
 I make my one map, and is retriveing the .pbf file but dont display anything, can you help me?
I think that is missing something in the style.json, i can't see the roads, poi, anything. Do you now why?

**Comment by randyhbh** [comment]
Any help?
